### ISSUE TITLE
False problems reported for sites with certificate from CAcert.org

### ISSUE THREAD

**Issue by wvdraay** [konklone/shaaaaaaaaaaaaa#74]
Please add the CAcert root certificate (https://www.cacert.org/certs/root.crt) to ca-bundle.crt to avoid false problem reports about sites with a certificate issued by CAcert.org.

**Comment by sebix** [comment]
See also the thread [SHA1 and cacert.org](https://lists.cacert.org/wws/arc/cacert/2015-02/msg00029.html) and especially [this message](https://lists.cacert.org/wws/arc/cacert/2015-02/msg00030.html) on the cacert@lists.cacert.org Mailinglist:

> The tool you are using is making a mistake. It appears to complain because
the CAcert *root* certificate (and not the CAcert Class 3 intermediate cert)
has an MD5 signature. This is *not* a security problem -- root certificates
need to be trusted outright, the digital signature hash employed is not an
issue. If Chrome gets it right, there won't be any warnings for cacert.org.

**Comment by konklone** [comment]
Fixed and discussed in #75, and now deployed:

https://shaaaaaaaaaaaaa.com/check/cacert.org

**Comment by wvdraay** [comment]
Thanks for the quick fix, very helpful!
