### ISSUE TITLE
Obsolete wording for google.com

### ISSUE THREAD

**Issue by selecadm** [konklone/shaaaaaaaaaaaaa#80]
https://shaaaaaaaaaaaaa.com/check/google.com

> Nice.
google.com has a verifiable certificate chain signed with SHA-2, and plans to migrate to SHA-2 in 2015.

![image](https://cloud.githubusercontent.com/assets/10382329/10443852/03755990-7168-11e5-87e2-adf17a2f27de.png)

**Comment by konklone** [comment]
Fixed in https://github.com/konklone/shaaaaaaaaaaaaa/commit/aa98c774eb58c9399c04647c79dcc1ad533f6548. Deploying momentarily (working out a auto-restart cronjob at the moment).
