### ISSUE TITLE
Add security headers to site

### ISSUE THREAD

**Issue by anand-bhat** [konklone/shaaaaaaaaaaaaa#85]
https://securityheaders.io/?q=https%3A%2F%2Fshaaaaaaaaaaaaa.com rates https://shaaaaaaaaaaaaa.com an 'E' due to the following missing headers:

* X-Frame-Options
* X-XSS-Protection
* X-Content-Type-Options
* Content-Security-Policy
* Public-Key-Pins

**Comment by konklone** [comment]
Thanks, but I'm not super concerned about lacking those headers for this site. There is no idea of login or users, so no XSS vulnerabilities, and no destructive actions that users could be fooled into if the site were used in a malicious iframe. Content Type Options prevents MIME sniffing, which I also don't care about. CSP and HPKP are similarly not necessary.

I may add HPKP _reporting_ at some point to test stuff out, but that's a separate issue.

**Comment by anand-bhat** [comment]
Fair enough, thanks for looking.
